# Change these first
owner: suptvdotorg # Your GitHub username
repo: suptv # Your GitHub repository name

# Add your sites here
sites:
  - name: Suptv
    url: https://www.suptv.org

status-website:
  theme: dark
  baseUrl: /suptv
  logoUrl: https://www.suptv.org/favicon.ico
  name: Suptv Statuss
  introTitle: Suptv Uptime & Status
  introMessage: This is a status page for suptv.org
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://www.suptv.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
